// SceneBuilder.BossFx.cs (Editor only)
// The thirty bosses' new ways of firing (2026-09-30: "not the same shot in another colour - a NEW way of firing for every boss; use the packs I
// downloaded"): Free Quick Effects Vol. 1 and Hovl's Magic Effects. Eight shapes (BossSpecial): a Sweep of fire or beam, a marked Zone that
// erupts, a Tornado that walks in, a Wave with one safe pocket, a lightning Chain, Portals that fire point blank, Spikes marching down a lane.
// No two bosses share a shape with the same effect, count and timing; each has a second, different one below half hp.
using System;
using UnityEngine;
using UnityEditor;

namespace SkySquad.EditorTools
{
    public static partial class SceneBuilder
    {
        static GameObject FxLoad(string path) { var p = AssetDatabase.LoadAssetAtPath<GameObject>(path); if (p == null) Debug.LogWarning("[SkySquad] effect missing: " + path); return p; }
        static GameObject Gq(string n) { return FxLoad("Assets/GabrielAguiarProductions/FreeQuickEffectsVol1/Prefabs/vfx_" + n + ".prefab"); }
        static GameObject Hv(string rel) { return FxLoad("Assets/Hovl Studio/Magic effects pack/Prefabs/" + rel + ".prefab"); }
        static Material BeamMat() { return AssetDatabase.LoadAssetAtPath<Material>(Gen + "/Materials/ParticleAdd.mat"); }

        static readonly Color CFire = new Color(1f, 0.45f, 0.1f), CBlue = new Color(0.35f, 0.7f, 1f), CGreen = new Color(0.35f, 1f, 0.45f), CPink = new Color(1f, 0.35f, 0.85f),
                              CGold = new Color(1f, 0.85f, 0.3f), CWhite = new Color(1f, 1f, 1f), CRed = new Color(1f, 0.25f, 0.25f), CPurple = new Color(0.65f, 0.35f, 1f);

        /// <summary>One boss attack: how he moves while he fights, how often he fires, then whatever 'set' makes of it.</summary>
        static BossAttack Nw(string name, float windup, MoveStyle mv, float range, float speed, float bob, float fire, string glow, Action<BossAttack> set)
        {
            var a = new BossAttack {
                name = name, windup = windup, move = mv, moveRange = range, moveSpeed = speed, bobRange = bob, fireEvery = fire, enrageVolley = 1, enrageFire = 0.7f, enrageAt = 0.5f,
                charge = Cfxr(glow), chargeScale = 1.2f, telegraph = true, shake = 0.2f, sound = Sfx.Boom };
            set(a);
            return a;
        }

        // The tells: a coloured circle laid where it will land, and the hits that burst there.
        static GameObject TellOrange() { return Hv("AoE effects/AoE slash orange"); }
        static GameObject TellBlue() { return Hv("AoE effects/AoE slash blue"); }
        static GameObject TellGreen() { return Hv("AoE effects/AoE slash green"); }
        static GameObject TellPink() { return Hv("Magic circles/Magic circle 2"); }
        static GameObject TellRune() { return Hv("Magic circles/Magic circle"); }

        static bool HaveBossFx() { return Gq("Flamethrower_01") != null && Hv("AoE effects/Ground AOE explosion") != null; }

        /// <summary>Boss N's opening attack (element N-1): a different shape and effect for every boss.</summary>
        static BossAttack[] BossAttacksNew()
        {
            var beam = BeamMat();
            var A = new BossAttack[BossCount];
            // ---- stage 1
            A[0] = Nw("fire bombs", 0.5f, MoveStyle.Sway, 0f, 1f, 0f, 3.6f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 2; a.radius = 1.7f; a.delay = 1.0f; a.fx = Gq("Flames_01"); a.fxScale = 2.2f; a.fxHit = Gq("Explosion_01"); a.hitScale = 4.5f; a.fxTell = TellOrange(); a.tellScale = 4.5f; a.volleyStagger = 0.35f; a.shake = 0.25f; });
            A[1] = Nw("flame sweep", 0.5f, MoveStyle.Sway, 1.0f, 0.6f, 0f, 4.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.LeftToRight; a.fx = Gq("Flamethrower_01"); a.fxScale = 2.6f; a.fxHit = Gq("Flames_01"); a.hitScale = 1.1f; a.duration = 2.4f; a.radius = 1.3f; a.tick = 0.25f; a.telegraph = false; a.sound = Sfx.Rocket; });
            A[2] = Nw("chain lightning", 0.5f, MoveStyle.Sway, 1.6f, 0.9f, 0f, 3.8f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Chain; a.count = 6; a.fx = Gq("Electricity_01"); a.fxScale = 1.6f; a.fxHit = Hv("Hits and explosions/Electro hit"); a.hitScale = 2.5f; a.volleyStagger = 0.16f; a.beamMat = beam; a.beamColor = CGold; a.beamWidth = 0.28f; a.telegraph = false; });
            A[3] = Nw("skull portals", 0.6f, MoveStyle.Dash, 3.0f, 1f, 0f, 3.8f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Portal; a.count = 3; a.delay = 0.9f; a.fx = Hv("Portals/Portal red"); a.fxScale = 2.8f; a.volleyStagger = 0.3f; a.projectile = Vfx("Range_attack/Projectiles_dark_magic"); a.projectileScale = 3f; a.hit = Cfxr("Misc/CFXR3 Hit Misc A"); a.muzzle = Vfx("Range_attack/Hit_dark_magic"); a.speedMul = 1.3f; a.sound = Sfx.Flak; });
            A[4] = Nw("laser wall", 0.8f, MoveStyle.Sway, 0.8f, 0.5f, 0f, 5.0f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Wave; a.delay = 1.6f; a.duration = 0f; a.gap = 1.3f; a.fx = Hv("AoE effects/Laser AOE"); a.fxScale = 1.3f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.35f; a.shake = 0.35f; a.telegraph = false; });
            // ---- stage 2
            A[5] = Nw("twister", 0.5f, MoveStyle.Sweep, 2.4f, 1.0f, 0f, 4.6f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Tornado; a.count = 2; a.fx = Gq("Tornado_01"); a.fxScale = 3f; a.radius = 1.5f; a.duration = 2.6f; a.homing = 2.8f; a.volleyStagger = 0.7f; a.shake = 0.15f; });
            A[6] = Nw("meteor shower", 0.6f, MoveStyle.Figure8, 1.6f, 0.8f, 0.4f, 4.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 3; a.radius = 2.0f; a.delay = 1.2f; a.hitDelay = 0.5f; a.fx = Gq("MeteorRain_01"); a.fxScale = 1.5f; a.fxHit = Gq("Explosion_02"); a.hitScale = 5f; a.fxTell = TellRune(); a.tellScale = 1.3f; a.volleyStagger = 0.4f; a.shake = 0.3f; });
            A[7] = Nw("flame jet", 0.5f, MoveStyle.Figure8, 2.0f, 1.0f, 0.5f, 4.2f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.RightToLeft; a.fx = Gq("Flamethrower_02"); a.fxScale = 2.8f; a.duration = 2.0f; a.radius = 1.3f; a.tick = 0.2f; a.telegraph = false; a.sound = Sfx.Rocket; });
            A[8] = Nw("crystal lanes", 0.6f, MoveStyle.Dash, 3.2f, 1f, 0f, 4.0f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Spikes; a.count = 2; a.fx = Hv("AoE effects/Crystals front attack"); a.fxScale = 1.4f; a.radius = 1.3f; a.steps = 7; a.duration = 1.4f; a.volleyStagger = 0.3f; a.fxHit = Hv("Hits and explosions/Snow hit"); a.hitScale = 3f; });
            A[9] = Nw("carpet bombing", 0.6f, MoveStyle.Sway, 1.8f, 0.7f, 0f, 4.6f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 5; a.radius = 1.5f; a.delay = 0.9f; a.fx = Gq("Explosion_02"); a.fxScale = 5f; a.fxHit = Hv("Hits and explosions/Explosion"); a.hitScale = 2f; a.volleyStagger = 0.18f; a.fxTell = TellOrange(); a.tellScale = 3.5f; a.shake = 0.35f; });
            // ---- stage 3
            A[10] = Nw("blizzard wall", 0.8f, MoveStyle.Sway, 1.5f, 0.8f, 0f, 5.0f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Wave; a.delay = 1.5f; a.duration = 0f; a.gap = 1.2f; a.fx = Hv("AoE effects/Snow AOE"); a.fxScale = 1.4f; a.fxTell = Hv("Magic circles/Freeze circle"); a.tellScale = 0.35f; a.shake = 0.3f; a.telegraph = false; });
            A[11] = Nw("storm chain", 0.5f, MoveStyle.Sway, 1.0f, 0.6f, 0f, 3.6f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Chain; a.count = 5; a.fx = Gq("Lightning_02"); a.fxScale = 4f; a.fxHit = Hv("Hits and explosions/Electro hit"); a.hitScale = 2.5f; a.volleyStagger = 0.12f; a.beamMat = beam; a.beamColor = CBlue; a.beamWidth = 0.4f; a.telegraph = false; });
            A[12] = Nw("green scanner", 0.5f, MoveStyle.Sweep, 3.4f, 2.0f, 0f, 3.6f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.Random; a.homing = 5f; a.beamMat = beam; a.beamColor = CGreen; a.beamWidth = 0.32f; a.fxHit = Hv("Hits and explosions/Green hit"); a.hitScale = 3f; a.duration = 2.2f; a.radius = 0.9f; a.tick = 0.18f; a.telegraph = true; a.sound = Sfx.Laser; });
            A[13] = Nw("sun lanterns", 0.7f, MoveStyle.Orbit, 2.0f, 0.9f, 0.8f, 4.6f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Zone; a.count = 2; a.radius = 2.4f; a.delay = 1.5f; a.fxTell = Gq("Implosion_01"); a.tellScale = 3f; a.fx = Hv("AoE effects/Red energy explosion"); a.fxScale = 0.9f; a.fxHit = Hv("Hits and explosions/Holy hit"); a.hitScale = 3f; a.volleyStagger = 0.5f; a.shake = 0.4f; });
            A[14] = Nw("plasma gates", 0.5f, MoveStyle.Sway, 2.2f, 1.2f, 0f, 3.8f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Portal; a.count = 3; a.delay = 0.7f; a.fx = Hv("Portals/Portal blue"); a.fxScale = 2.6f; a.volleyStagger = 0.22f; a.projectile = Vfx("Range_attack/Projectiles_magic"); a.projectileScale = 3f; a.hit = Cfxr("Eerie/CFXR2 WW Enemy Explosion"); a.muzzle = Vfx("Range_attack/Hit_magic"); a.speedMul = 1.5f; a.sound = Sfx.Laser; });
            // ---- stage 4
            A[15] = Nw("jade thorns", 0.6f, MoveStyle.Figure8, 2.6f, 1.1f, 0.5f, 4.0f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Spikes; a.count = 3; a.fx = Hv("AoE effects/Crystals crossfade 2"); a.fxScale = 0.45f; a.radius = 1.2f; a.steps = 8; a.duration = 1.5f; a.volleyStagger = 0.25f; a.fxHit = Hv("Hits and explosions/Green hit"); a.hitScale = 3f; });
            A[16] = Nw("reaper rings", 0.5f, MoveStyle.Dash, 3.4f, 1f, 0f, 3.0f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Zone; a.count = 4; a.radius = 1.6f; a.delay = 0.8f; a.fx = Hv("AoE effects/Ground AOE explosion"); a.fxScale = 1.1f; a.fxTell = TellPink(); a.tellScale = 1.2f; a.volleyStagger = 0.2f; a.shake = 0.25f; });
            A[17] = Nw("ivory beam", 1.0f, MoveStyle.Sweep, 3.0f, 0.9f, 0f, 4.4f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.Random; a.homing = 2.2f; a.beamMat = beam; a.beamColor = CWhite; a.beamWidth = 0.9f; a.fxHit = Hv("Hits and explosions/Holy hit"); a.hitScale = 4f; a.duration = 2.8f; a.radius = 1.2f; a.tick = 0.25f; a.shake = 0.3f; a.sound = Sfx.Laser; });
            A[18] = Nw("fire walkers", 0.6f, MoveStyle.Sway, 0.8f, 0.5f, 0f, 5.2f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Tornado; a.count = 3; a.fx = Gq("Flames_01"); a.fxScale = 2.6f; a.radius = 1.6f; a.duration = 3.2f; a.homing = 1.8f; a.volleyStagger = 0.9f; a.shake = 0.2f; });
            A[19] = Nw("black hole", 0.8f, MoveStyle.Orbit, 1.6f, 1.0f, 0.9f, 5.0f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Zone; a.count = 1; a.radius = 3.0f; a.delay = 1.9f; a.fxTell = Gq("Implosion_01"); a.tellScale = 4.5f; a.fx = Hv("AoE effects/Smoke AOE explosion"); a.fxScale = 1.4f; a.fxHit = Gq("Explosion_01"); a.hitScale = 7f; a.shake = 0.5f; });
            // ---- stage 5
            A[20] = Nw("golden shockwave", 0.7f, MoveStyle.Figure8, 2.4f, 1.2f, 0.7f, 4.2f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Wave; a.delay = 1.3f; a.duration = 1.2f; a.gap = 1.2f; a.fx = Gq("Shockwave_01"); a.fxScale = 5f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.35f; a.fxHit = Hv("Hits and explosions/Holy hit"); a.hitScale = 3f; a.shake = 0.35f; a.telegraph = false; });
            A[21] = Nw("pink gates", 0.4f, MoveStyle.Sweep, 3.6f, 2.2f, 0f, 3.0f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Portal; a.count = 5; a.delay = 0.6f; a.fx = Hv("Portals/Portal yellow"); a.fxScale = 2.4f; a.volleyStagger = 0.1f; a.projectile = Vfx("Range_attack/Projectiles_heart"); a.projectileScale = 3f; a.hit = Cfxr("Eerie/CFXR2 WW Enemy Explosion"); a.muzzle = Vfx("Range_attack/Hit_heart"); a.speedMul = 1.7f; a.sound = Sfx.Laser; });
            A[22] = Nw("dragon jets", 0.6f, MoveStyle.Figure8, 2.8f, 0.9f, 0.8f, 4.6f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.OutsideIn; a.fx = Gq("Flamethrower_02"); a.fxScale = 3f; a.fxHit = Gq("Flames_01"); a.hitScale = 1.2f; a.duration = 2.4f; a.radius = 1.3f; a.tick = 0.2f; a.telegraph = false; a.shake = 0.3f; a.sound = Sfx.Rocket; });
            A[23] = Nw("stone lanes", 0.4f, MoveStyle.Dash, 3.6f, 1f, 0f, 3.2f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Spikes; a.count = 3; a.fx = Hv("AoE effects/Crystals front attack"); a.fxScale = 1.2f; a.radius = 1.1f; a.steps = 6; a.duration = 0.9f; a.volleyStagger = 0.15f; a.fxHit = Hv("Hits and explosions/Stones hit"); a.hitScale = 3f; });
            A[24] = Nw("sky fortress rain", 1.0f, MoveStyle.Sway, 1.0f, 0.5f, 0f, 5.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 4; a.radius = 2.2f; a.delay = 1.4f; a.hitDelay = 0.6f; a.fx = Gq("MeteorRain_02"); a.fxScale = 1.6f; a.fxHit = Gq("Explosion_02"); a.hitScale = 6f; a.fxTell = TellBlue(); a.tellScale = 5f; a.volleyStagger = 0.3f; a.shake = 0.4f; });
            // ---- stage 6
            A[25] = Nw("void web", 0.5f, MoveStyle.Orbit, 2.2f, 1.1f, 0.8f, 3.8f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Chain; a.count = 7; a.fx = Gq("Impact_01"); a.fxScale = 3f; a.fxHit = Hv("Hits and explosions/Love hit"); a.hitScale = 3f; a.volleyStagger = 0.11f; a.beamMat = beam; a.beamColor = CPurple; a.beamWidth = 0.3f; a.telegraph = false; });
            A[26] = Nw("crescent beams", 0.7f, MoveStyle.Sweep, 3.2f, 1.2f, 0f, 4.4f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.LeftToRight; a.beamMat = beam; a.beamColor = CBlue; a.beamWidth = 0.55f; a.fxHit = Hv("Hits and explosions/Snow hit"); a.hitScale = 3f; a.duration = 1.6f; a.radius = 1.0f; a.tick = 0.16f; a.telegraph = false; a.sound = Sfx.Laser; });
            A[27] = Nw("inferno storm", 0.8f, MoveStyle.Figure8, 3.0f, 1.0f, 1.0f, 4.8f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Tornado; a.count = 2; a.fx = Gq("Flames_01"); a.fxScale = 3.2f; a.radius = 1.7f; a.duration = 2.2f; a.homing = 3.6f; a.volleyStagger = 0.5f; a.fxHit = Gq("Explosion_02"); a.hitScale = 5f; a.shake = 0.4f; });
            A[28] = Nw("star collapse", 0.9f, MoveStyle.Orbit, 2.4f, 1.0f, 0.8f, 4.8f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Zone; a.count = 3; a.radius = 2.0f; a.delay = 1.4f; a.fxTell = Gq("Implosion_01"); a.tellScale = 3.2f; a.fx = Hv("AoE effects/Plexus AoE"); a.fxScale = 1.4f; a.fxHit = Hv("Hits and explosions/Star hit"); a.hitScale = 4f; a.volleyStagger = 0.4f; a.shake = 0.4f; });
            A[29] = Nw("overlord wall", 1.0f, MoveStyle.Sweep, 3.0f, 0.8f, 0f, 5.2f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Wave; a.delay = 1.8f; a.duration = 1.6f; a.gap = 1.0f; a.fx = Hv("AoE effects/Red energy explosion"); a.fxScale = 1.4f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.3f; a.fxHit = Gq("Explosion_01"); a.hitScale = 5f; a.shake = 0.5f; a.telegraph = false; });
            return A;
        }

        /// <summary>Boss N's second attack, below half hp: a different shape from his first, and he fires faster and with more.</summary>
        static BossAttack[] BossAttacksNew2()
        {
            var beam = BeamMat();
            var B = new BossAttack[BossCount];
            B[0] = Nw("flame sweep", 0.4f, MoveStyle.Sway, 1.4f, 1.0f, 0f, 3.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.RightToLeft; a.fx = Gq("Flamethrower_01"); a.fxScale = 2.8f; a.duration = 2.0f; a.radius = 1.4f; a.tick = 0.2f; a.telegraph = false; a.sound = Sfx.Rocket; });
            B[1] = Nw("whirlwind", 0.4f, MoveStyle.Sweep, 2.6f, 1.2f, 0f, 3.8f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Tornado; a.count = 2; a.fx = Gq("Tornado_01"); a.fxScale = 3f; a.radius = 1.5f; a.duration = 2.2f; a.homing = 3.4f; a.volleyStagger = 0.5f; });
            B[2] = Nw("hunter beam", 0.5f, MoveStyle.Sway, 2.0f, 1.0f, 0f, 3.6f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.Random; a.homing = 4f; a.beamMat = beam; a.beamColor = CBlue; a.beamWidth = 0.45f; a.fxHit = Hv("Hits and explosions/Electro hit"); a.hitScale = 3f; a.duration = 2.4f; a.radius = 1.0f; a.tick = 0.18f; a.telegraph = true; a.sound = Sfx.Laser; });
            B[3] = Nw("smoke bombs", 0.4f, MoveStyle.Dash, 3.4f, 1.2f, 0f, 3.2f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Zone; a.count = 3; a.radius = 1.8f; a.delay = 0.9f; a.fx = Hv("AoE effects/Smoke AOE explosion"); a.fxScale = 1.0f; a.fxTell = TellPink(); a.tellScale = 1.3f; a.volleyStagger = 0.25f; });
            B[4] = Nw("storm chain", 0.4f, MoveStyle.Sway, 1.2f, 0.8f, 0f, 3.4f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Chain; a.count = 8; a.fx = Gq("Lightning_01"); a.fxScale = 4f; a.fxHit = Hv("Hits and explosions/Electro hit"); a.hitScale = 2.5f; a.volleyStagger = 0.1f; a.beamMat = beam; a.beamColor = CGold; a.beamWidth = 0.3f; a.telegraph = false; });
            B[5] = Nw("twin twisters", 0.3f, MoveStyle.Sweep, 3.4f, 2.0f, 0f, 3.0f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Tornado; a.count = 4; a.fx = Gq("Tornado_01"); a.fxScale = 3f; a.radius = 1.4f; a.duration = 1.8f; a.homing = 4.4f; a.volleyStagger = 0.35f; });
            B[6] = Nw("yellow gates", 0.4f, MoveStyle.Figure8, 1.8f, 1.0f, 0.4f, 3.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Portal; a.count = 4; a.delay = 0.7f; a.fx = Hv("Portals/Portal yellow"); a.fxScale = 2.6f; a.volleyStagger = 0.2f; a.projectile = Vfx("Range_attack/Projectiles_fire"); a.projectileScale = 3f; a.hit = Cfxr("Fire/CFXR3 Hit Fire B (Air)"); a.muzzle = Vfx("Range_attack/Hit_fire"); a.speedMul = 1.6f; a.sound = Sfx.Rocket; });
            B[7] = Nw("fire rain", 0.4f, MoveStyle.Figure8, 2.4f, 1.2f, 0.6f, 3.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 5; a.radius = 1.6f; a.delay = 0.8f; a.fx = Gq("Flames_01"); a.fxScale = 2.2f; a.fxHit = Gq("Explosion_01"); a.hitScale = 4.5f; a.fxTell = TellOrange(); a.tellScale = 4f; a.volleyStagger = 0.16f; });
            B[8] = Nw("moon slashes", 0.3f, MoveStyle.Dash, 3.6f, 1.3f, 0f, 2.8f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Spikes; a.count = 4; a.fx = Hv("AoE effects/Crystals front attack"); a.fxScale = 1.3f; a.radius = 1.2f; a.steps = 6; a.duration = 1.0f; a.volleyStagger = 0.18f; a.fxHit = Hv("Hits and explosions/Snow hit"); a.hitScale = 3f; });
            B[9] = Nw("shock ring", 0.5f, MoveStyle.Sway, 1.8f, 0.9f, 0f, 3.6f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Wave; a.delay = 1.4f; a.duration = 0f; a.gap = 1.2f; a.fx = Hv("AoE effects/Red energy explosion"); a.fxScale = 1.3f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.35f; a.shake = 0.35f; a.telegraph = false; });
            B[10] = Nw("ice fields", 0.4f, MoveStyle.Sweep, 3.0f, 1.6f, 0f, 3.2f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Zone; a.count = 3; a.radius = 2.2f; a.delay = 1.0f; a.fx = Hv("AoE effects/Snow AOE"); a.fxScale = 0.9f; a.fxTell = Hv("Magic circles/Freeze circle"); a.tellScale = 0.28f; a.volleyStagger = 0.3f; });
            B[11] = Nw("thunder beams", 0.5f, MoveStyle.Sway, 1.4f, 0.9f, 0f, 3.6f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.CenterOut; a.beamMat = beam; a.beamColor = CGold; a.beamWidth = 0.5f; a.fxHit = Hv("Hits and explosions/Electro hit"); a.hitScale = 3f; a.duration = 1.8f; a.radius = 1.0f; a.tick = 0.16f; a.telegraph = false; a.sound = Sfx.Laser; });
            B[12] = Nw("green gates", 0.3f, MoveStyle.Sweep, 3.6f, 2.4f, 0f, 2.8f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Portal; a.count = 5; a.delay = 0.6f; a.fx = Hv("Portals/Portal green"); a.fxScale = 2.4f; a.volleyStagger = 0.12f; a.projectile = Vfx("Range_attack/Projectiles_green_shuriken"); a.projectileScale = 3f; a.hit = Cfxr("Impacts/CFXR Hit A (Red)"); a.speedMul = 1.7f; a.sound = Sfx.Flak; });
            B[13] = Nw("solar beams", 0.6f, MoveStyle.Orbit, 2.4f, 1.1f, 0.9f, 3.6f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.OutsideIn; a.beamMat = beam; a.beamColor = CGold; a.beamWidth = 0.6f; a.fxHit = Hv("Hits and explosions/Holy hit"); a.hitScale = 3.5f; a.duration = 2.0f; a.radius = 1.1f; a.tick = 0.16f; a.telegraph = false; a.sound = Sfx.Laser; });
            B[14] = Nw("crystal lanes", 0.4f, MoveStyle.Sway, 2.6f, 1.2f, 0f, 3.4f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Spikes; a.count = 3; a.fx = Hv("AoE effects/Crystals front attack"); a.fxScale = 1.3f; a.radius = 1.2f; a.steps = 7; a.duration = 1.2f; a.volleyStagger = 0.22f; a.fxHit = Hv("Hits and explosions/Snow hit"); a.hitScale = 3f; });
            B[15] = Nw("jade lightning", 0.4f, MoveStyle.Figure8, 2.8f, 1.3f, 0.6f, 3.2f, "Electric/CFXR Electrified 3", a => { a.kind = AttackKind.Chain; a.count = 6; a.fx = Gq("Electricity_01"); a.fxScale = 1.6f; a.fxHit = Hv("Hits and explosions/Green hit"); a.hitScale = 3f; a.volleyStagger = 0.12f; a.beamMat = beam; a.beamColor = CGreen; a.beamWidth = 0.3f; a.telegraph = false; });
            B[16] = Nw("reaper storm", 0.3f, MoveStyle.Dash, 3.6f, 1.4f, 0f, 2.4f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Zone; a.count = 6; a.radius = 1.6f; a.delay = 0.7f; a.fx = Hv("AoE effects/Ground AOE explosion"); a.fxScale = 1.1f; a.fxTell = TellPink(); a.tellScale = 1.2f; a.volleyStagger = 0.14f; });
            B[17] = Nw("ivory wall", 0.8f, MoveStyle.Sweep, 3.2f, 1.2f, 0f, 3.6f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Wave; a.delay = 1.3f; a.duration = 0f; a.gap = 1.0f; a.fx = Hv("AoE effects/Laser AOE"); a.fxScale = 1.3f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.3f; a.shake = 0.4f; a.telegraph = false; });
            B[18] = Nw("titan shells", 0.5f, MoveStyle.Sway, 1.2f, 0.7f, 0f, 4.2f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 6; a.radius = 1.5f; a.delay = 0.9f; a.fx = Gq("Explosion_02"); a.fxScale = 5f; a.fxTell = TellOrange(); a.tellScale = 3.5f; a.volleyStagger = 0.14f; a.shake = 0.35f; });
            B[19] = Nw("red gates", 0.4f, MoveStyle.Orbit, 1.8f, 1.2f, 1.0f, 3.4f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Portal; a.count = 5; a.delay = 0.7f; a.fx = Hv("Portals/Portal red"); a.fxScale = 2.6f; a.volleyStagger = 0.15f; a.projectile = Vfx("Range_attack/Projectiles_magic"); a.projectileScale = 3.2f; a.hit = Cfxr("Eerie/CFXR2 WW Enemy Explosion"); a.muzzle = Vfx("Range_attack/Hit_magic"); a.speedMul = 1.6f; a.sound = Sfx.Laser; });
            B[20] = Nw("golden chain", 0.4f, MoveStyle.Figure8, 2.6f, 1.3f, 0.8f, 3.2f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Chain; a.count = 7; a.fx = Gq("Lightning_01"); a.fxScale = 4f; a.fxHit = Hv("Hits and explosions/Holy hit"); a.hitScale = 3f; a.volleyStagger = 0.1f; a.beamMat = beam; a.beamColor = CGold; a.beamWidth = 0.35f; a.telegraph = false; });
            B[21] = Nw("pink beam", 0.5f, MoveStyle.Sweep, 3.8f, 2.6f, 0f, 3.0f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.LeftToRight; a.beamMat = beam; a.beamColor = CPink; a.beamWidth = 0.5f; a.fxHit = Hv("Hits and explosions/Love hit"); a.hitScale = 3f; a.duration = 1.5f; a.radius = 1.0f; a.tick = 0.14f; a.telegraph = false; a.sound = Sfx.Laser; });
            B[22] = Nw("dragon rain", 0.4f, MoveStyle.Figure8, 3.0f, 1.2f, 0.9f, 3.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 6; a.radius = 1.5f; a.delay = 0.8f; a.fx = Gq("Flames_01"); a.fxScale = 2.2f; a.fxHit = Gq("Explosion_01"); a.hitScale = 4f; a.fxTell = TellOrange(); a.tellScale = 4f; a.volleyStagger = 0.13f; });
            B[23] = Nw("hornet twisters", 0.3f, MoveStyle.Dash, 3.8f, 1.6f, 0f, 2.6f, "Nature/CFXR4 Wind Trails", a => { a.kind = AttackKind.Tornado; a.count = 3; a.fx = Gq("Tornado_01"); a.fxScale = 2.6f; a.radius = 1.3f; a.duration = 1.6f; a.homing = 5f; a.volleyStagger = 0.3f; });
            B[24] = Nw("fortress wall", 0.8f, MoveStyle.Sway, 1.4f, 0.7f, 0f, 4.4f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Wave; a.delay = 1.4f; a.duration = 1.0f; a.gap = 1.0f; a.fx = Gq("Shockwave_01"); a.fxScale = 5f; a.fxTell = Hv("Magic circles/Healing circle"); a.tellScale = 0.3f; a.fxHit = Gq("Explosion_02"); a.hitScale = 5f; a.shake = 0.5f; a.telegraph = false; });
            B[25] = Nw("void gates", 0.4f, MoveStyle.Orbit, 2.6f, 1.2f, 0.9f, 3.0f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Portal; a.count = 6; a.delay = 0.6f; a.fx = Hv("Portals/Portal blue"); a.fxScale = 2.4f; a.volleyStagger = 0.11f; a.projectile = Vfx("Range_attack/Projectiles_dark_magic"); a.projectileScale = 3f; a.hit = Cfxr("Misc/CFXR3 Hit Misc A"); a.muzzle = Vfx("Range_attack/Hit_dark_magic"); a.speedMul = 1.8f; a.sound = Sfx.Flak; });
            B[26] = Nw("crystal storm", 0.4f, MoveStyle.Sweep, 3.4f, 1.6f, 0f, 3.0f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Spikes; a.count = 4; a.fx = Hv("AoE effects/Crystals front attack"); a.fxScale = 1.4f; a.radius = 1.2f; a.steps = 7; a.duration = 1.1f; a.volleyStagger = 0.16f; a.fxHit = Hv("Hits and explosions/Snow hit"); a.hitScale = 3f; });
            B[27] = Nw("meteor storm", 0.6f, MoveStyle.Figure8, 3.2f, 1.2f, 1.0f, 3.6f, "Fire/CFXR Fire", a => { a.kind = AttackKind.Zone; a.count = 6; a.radius = 1.8f; a.delay = 0.9f; a.hitDelay = 0.4f; a.fx = Gq("MeteorRain_01"); a.fxScale = 1.4f; a.fxHit = Gq("Explosion_02"); a.hitScale = 5f; a.fxTell = TellRune(); a.tellScale = 1.3f; a.volleyStagger = 0.14f; a.shake = 0.4f; });
            B[28] = Nw("star beams", 0.5f, MoveStyle.Orbit, 2.8f, 1.3f, 1.0f, 3.4f, "Magic Misc/CFXR3 Magic Aura A (Runic)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.CenterOut; a.beamMat = beam; a.beamColor = CPurple; a.beamWidth = 0.55f; a.fxHit = Hv("Hits and explosions/Star hit"); a.hitScale = 3.5f; a.duration = 2.0f; a.radius = 1.1f; a.tick = 0.15f; a.telegraph = false; a.sound = Sfx.Laser; });
            B[29] = Nw("final beams", 0.6f, MoveStyle.Sweep, 3.4f, 1.4f, 0f, 3.4f, "Light/CFXR3 LightGlow A (Loop)", a => { a.kind = AttackKind.Sweep; a.order = ShotOrder.OutsideIn; a.beamMat = beam; a.beamColor = CRed; a.beamWidth = 0.7f; a.fxHit = Gq("Explosion_01"); a.hitScale = 3f; a.duration = 2.0f; a.radius = 1.2f; a.tick = 0.14f; a.telegraph = false; a.shake = 0.4f; a.sound = Sfx.Laser; });
            return B;
        }
    }
}
